# 1. Site Settings
title               : r00t26
owner               : "Lazus Imperius"
url                 : "https://r00t26.com/"
baseurl             : "/"
permalink           : /:title/
description         : "A website dedicated to offensive cyber security."
markdown            : kramdown
statement           : "Designed by DeerRIDER, All Rights Reserved"
bgtext              : "абвгдеёжзийклмнопрстуфхцчшщъыьэюя*+-;/[]<>~" # texts randomly displayed in background

# 2.Collections

collections:
  hacking:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Hacking Techniques"
  cheatsheets:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Cheatsheets"
  theory:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Theory & Concepts"
  analysis:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Analysis & Scanning"
  osint:
    output          : true
    permalink       : /:collection/:title/
    alias           : "Open Source Intelligence"

# 3. Comment settings（disqus.com）
#disqus_username     : 

# 4. Default page settings (WILL BE overwriten by front-matters of a page)
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
    values:
      layout              : "post"      # which layout to use by default
      publish             : true        # whether to show by default      
      btn_text            : true        # whether show button text by default
      collection_list     : true        # whether show archive button by default
      home_btn            : true        # whether show home by default
      maximize            : true        # whether show maximize button by default
      encrypted_text      : false       # whether use encrytion function by default
      toc                 : true        # whether show table of content by default
      toc_level           : 3           # the toc depth by default
      author              : "Lazus Imperius" # author name by default
      show_date           : true        # whether show date message by default
      category            :             # category by default
      post_list           : false       # whether show list of post by default      
      comment             : false
      footer              : true        # whether show footer by default
      http_headers:
        X-Frame-Options   : "SAMEORIGIN"  # Adding X-Frame-Options header to mitigate clickjacking
        X-Content-Type-Options: "nosniff" # Adding X-Content-Type-Options header to prevent MIME-sniffing attacks
        

# 5. Social Media Accounts
email               : "lazus.imperius@gmail.com"
github              : "r00t26"
#instagram           :
#youtube             :

# 6. Where things are
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

# 7. Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

gems: [jekyll-mermaid]

# 8. Others
# Cross-Origin Resource Sharing header
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
